apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  USER_SERVICE_URL: "http://user-service:5001"
  PRODUCT_SERVICE_URL: "http://product-service:5002"
  PAYMENT_SERVICE_URL: "http://payment-service:5004"