apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: 847283080148.dkr.ecr.ap-south-1.amazonaws.com/cloud-native-devops/payment-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: SERVICE_NAME
              value: "payment-service"
            - name: SERVICE_PORT
              value: "5004"
